### ISSUE TITLE
Incorrect or duplicate messages displayed in azuremysqlmigfinal.sh

### ISSUE THREAD

**Issue by m-ueta** [Azure/azure-mysql#91]
This is exactly what I wrote in the title (and attached file).
![screenshot](https://user-images.githubusercontent.com/7521134/150476433-63744d95-25f4-4e07-b0f3-faa95e66a011.png)

I have created a small pullrequest　[#88], please refer to it.

**Comment by SudheeshGH** [comment]
Correct the Script

**Comment by m-ueta** [comment]
> Correct the Script

I just didn't understand how it could be correct when different values are returned for the same label(key).

I think it should be `Source password` , but it is `Source User Name` .
Could you please tell me what is correct?
